# Generated by Django 5.2.7 on 2025-10-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da equipe')),
                ('usuario', models.CharField(max_length=100, verbose_name='Nome do usuário que utilizou para seguir a apresentação')),
                ('membro1', models.CharField(max_length=100, verbose_name='Membro 1')),
                ('membro2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Membro 2')),
            ],
        ),
    ]
